// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC5CidyXSi_-Zi2TQ99R4NRUpyah3ClxU',
    appId: '1:653994527968:web:472ac47302e3ee7a0c5485',
    messagingSenderId: '653994527968',
    projectId: 'employee-db-addf5',
    authDomain: 'employee-db-addf5.firebaseapp.com',
    databaseURL: 'https://employee-db-addf5-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-addf5.appspot.com',
    measurementId: 'G-PPYK1PE1SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-01lFTgav7Ad5lbrjE6yT6N47FP5-Rc',
    appId: '1:653994527968:android:382758b5d97cdfc90c5485',
    messagingSenderId: '653994527968',
    projectId: 'employee-db-addf5',
    databaseURL: 'https://employee-db-addf5-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-addf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKXChC8s0dIr6Agip5WUuDqs8R_XDmAU',
    appId: '1:653994527968:ios:5f74d1828a9fbe550c5485',
    messagingSenderId: '653994527968',
    projectId: 'employee-db-addf5',
    databaseURL: 'https://employee-db-addf5-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-addf5.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeKXChC8s0dIr6Agip5WUuDqs8R_XDmAU',
    appId: '1:653994527968:ios:5f74d1828a9fbe550c5485',
    messagingSenderId: '653994527968',
    projectId: 'employee-db-addf5',
    databaseURL: 'https://employee-db-addf5-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-addf5.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC5CidyXSi_-Zi2TQ99R4NRUpyah3ClxU',
    appId: '1:653994527968:web:1040c4ee75c8d46d0c5485',
    messagingSenderId: '653994527968',
    projectId: 'employee-db-addf5',
    authDomain: 'employee-db-addf5.firebaseapp.com',
    databaseURL: 'https://employee-db-addf5-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-addf5.appspot.com',
    measurementId: 'G-18S77G486C',
  );
}
